project:
  type: website
  output-dir: docs

website:
  title: "Python Installation Support - Onboarding Guide"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    toc-depth: 3
    toc-location: left
    code-fold: false
    code-tools: false
    smooth-scroll: true
  pdf:
    documentclass: scrreprt
    toc: true
  docx:
    toc: true
